<Project>
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <Platforms>x64</Platforms>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
    </PropertyGroup>
</Project>
